FinalProjectThatWorks.UI.MVC/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
//Needed for Image Upload Utility
using System.Drawing;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FinalProjectThatWorks.DATA.EF;
using FinalProjectThatWorks.UI.MVC.Utilties;
using Microsoft.AspNet.Identity;

namespace FinalProjectThatWorks.UI.MVC.Controllers
{
    public class CarsController : Controller
    {
        private FinalProject2Entities db = new FinalProject2Entities();

        // GET: Cars
        public ActionResult Index()
        {
            string user = User.Identity.GetUserId();
            var cars = db.Cars.Include(c => c.UserDetail);
            if (User.IsInRole("Owner"))
            {
                cars = cars.Where(c => c.OwnerId == user);
            }
            return View(cars.ToList());
        }
        
        // GET: Cars/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = db.Cars.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        //Only available in Owner and Admin Roles.
        [Authorize(Roles = "Admin")]        
        [Authorize(Roles = "Owner")]
        // GET: Cars/Create
        public ActionResult Create()
        {
            ViewBag.OwnerId = new SelectList(db.UserDetails, "UserId", "FirstName");
            return View();
        }

        //Only available in Owner and Admin Roles.
        [Authorize(Roles = "Admin")]
        [Authorize(Roles = "Owner")]
        // POST: Cars/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OwnerAssetId,CarName,OwnerId,CarPhoto,SpecialNotes,IsActive,DateAdded")] Car car, HttpPostedFileBase CarPhoto)
        {
            #region File Upload
            if (ModelState.IsValid)
            {
                //Use default image if none is provided.
                string imgName = "GenericCar.jpg";
                if (CarPhoto != null) //HttpPostedFileBase added to the action != null
                {
                    //Get image and return to variable.
                    imgName = CarPhoto.FileName;

                    //Declare and assign ext variable.
                    string ext = imgName.Substring(imgName.LastIndexOf('.'));

                    //Declare a list of valid extensions.
                    string[] goodExts = { ".jpeg", ".jpg", ".gif", ".png" };

                    //Check the ext variable (toLower()) against the valid list.
                    if (goodExts.Contains(ext.ToLower()) && (CarPhoto.ContentLength <= 4194304))//Max 4MB value allowed by ASP.net
                    {
                        //If it is in the list using a guid
                        imgName = Guid.NewGuid() + ext;

                        //save to the webserver
                       CarPhoto.SaveAs(Server.MapPath("~/Content/assets/img/" + imgName));

                        //Create variables to resize image.
                        string savePath = Server.MapPath("~/Content/assets/img/");

                        Image convertedImage = Image.FromStream(CarPhoto.InputStream);

                        int maxImgSize = 500;
                        int maxThumbSize = 100;

                        UploadUtility.ResizeImage(savePath, imgName, convertedImage, maxImgSize, maxThumbSize);
                    }
                    else
                    {
                        imgName = "GenericCar.jpg";
                    }

                    //No matter what, add imgName to the object.
                    car.CarPhoto = imgName;
                }

            }
            #endregion  
            if (ModelState.IsValid)
            {
                db.Cars.Add(car);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.OwnerId = new SelectList(db.UserDetails, "UserId", "FirstName", car.OwnerId);
            return View(car);
        }

        //Only available in Owner and Admin Roles.
        [Authorize(Roles = "Admin")]
        [Authorize(Roles = "Owner")]
        // GET: Cars/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = db.Cars.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            ViewBag.OwnerId = new SelectList(db.UserDetails, "UserId", "FirstName", car.OwnerId);
            return View(car);
        }

        //Only available in Owner and Admin Roles.
        [Authorize(Roles = "Admin")]
        [Authorize(Roles = "Owner")]
        // POST: Cars/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OwnerAssetId,CarName,OwnerId,CarPhoto,SpecialNotes,IsActive,DateAdded")] Car car, HttpPostedFileBase CarPhoto)
        {
            #region File Upload
            if (CarPhoto != null)//HttpPostedFileBase added to the action != null
            {
                //Get image and assign to variable
                string imgName = CarPhoto.FileName;

                //Declare and assign ext value
                string ext = imgName.Substring(imgName.LastIndexOf('.'));

                //Declare a list of valid extensions.
                string[] goodExts = { ".jpeg", ".jpg", ".gif", ".png" };

                //Check the ext value (toLower()) against the valid list
                if (goodExts.Contains(ext.ToLower()) && (CarPhoto.ContentLength <= 4194304))//4MB max allowed by ASP.NET
                {
                    //If it is in the list rename using a guid
                    imgName = Guid.NewGuid() + ext;

                    //Save to the webserver
                    CarPhoto.SaveAs(Server.MapPath("~/Content/assets/img/" + imgName));

                    //Create variables to resize image.
                    string savePath = Server.MapPath("~/Content/assets/img/");

                    Image convertedImage = Image.FromStream(CarPhoto.InputStream);

                    int maxImgSize = 500;
                    int maxThumbSize = 100;

                    UploadUtility.ResizeImage(savePath, imgName, convertedImage, maxImgSize, maxThumbSize);

                    //Make sure you are not deleting your default image.
                    if (car.CarPhoto != null && car.CarPhoto != "GenericCar.jpg")
                    {
                        //Remove the original file
                        string path = Server.MapPath("~/Content/assets/img/");
                        UploadUtility.Delete(path, car.CarPhoto);
                    }

                    //Only save if image meets criteria imageName to the object.
                    car.CarPhoto = imgName;
                }

            }
            #endregion
            if (ModelState.IsValid)
            {
                db.Entry(car).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.OwnerId = new SelectList(db.UserDetails, "UserId", "FirstName", car.OwnerId);
            return View(car);
        }

        //Only available in Admin Role.
        [Authorize(Roles = "Admin")]
        // GET: Cars/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = db.Cars.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        //Only available in Admin Role.
        [Authorize(Roles = "Admin")]
        // POST: Cars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Car car = db.Cars.Find(id);

            if (car.CarPhoto != null && car.CarPhoto != "GenericCar.jpg")
            {
                //Remove the original file from the edit view.
                string path = Server.MapPath("~/Content/assets/img/");
                UploadUtility.Delete(path, car.CarPhoto);
            }

            db.Cars.Remove(car);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FinalProjectThatWorks.UI.MVC/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FinalProjectThatWorks.DATA.EF;

namespace FinalProjectThatWorks.UI.MVC.Controllers
{
    public class LocationsController : Controller
    {
        private FinalProject2Entities db = new FinalProject2Entities();

        // GET: Locations
        public ActionResult Index()
        {
            return View(db.Locations.ToList());
        }

        // GET: Locations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        //Only available in Admin Role.
        [Authorize(Roles = "Admin")]
        // GET: Locations/Create
        public ActionResult Create()
        {
            return View();
        }

        //Only available in Admin Role.
        [Authorize(Roles = "Admin")]
        // POST: Locations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LocationId,LocationName,Address,City,State,ZipCode,ReservationLimit")] Location location)
        {
            if (ModelState.IsValid)
            {
                db.Locations.Add(location);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(location);
        }

        //Only available in Admin Role.
        [Authorize(Roles = "Admin")]        
        // GET: Locations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        //Only available in Admin Role.
        [Authorize(Roles = "Admin")]
        // POST: Locations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LocationId,LocationName,Address,City,State,ZipCode,ReservationLimit")] Location location)
        {
            if (ModelState.IsValid)
            {
                db.Entry(location).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(location);
        }

        //Only available in Admin Role.
        [Authorize(Roles = "Admin")]
        // GET: Locations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        //Only available in Admin Role.
        [Authorize(Roles = "Admin")]
        // POST: Locations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Location location = db.Locations.Find(id);
            db.Locations.Remove(location);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FinalProjectThatWorks.UI.MVC/Controllers/UserDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FinalProjectThatWorks.DATA.EF;

namespace FinalProjectThatWorks.UI.MVC.Controllers
{
    public class UserDetailsController : Controller
    {
        private FinalProject2Entities db = new FinalProject2Entities();

        [Authorize(Roles = "Admin")]
        // GET: UserDetails
        public ActionResult Index()
        {
            return View(db.UserDetails.ToList());
        }

        [Authorize(Roles = "Admin")]
        // GET: UserDetails/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserDetail userDetail = db.UserDetails.Find(id);
            if (userDetail == null)
            {
                return HttpNotFound();
            }
            return View(userDetail);
        }

        [Authorize(Roles = "Admin")]
        // GET: UserDetails/Create
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        // POST: UserDetails/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserId,FirstName,LastName")] UserDetail userDetail)
        {
            if (ModelState.IsValid)
            {
                db.UserDetails.Add(userDetail);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(userDetail);
        }

        [Authorize(Roles = "Admin")]
        // GET: UserDetails/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserDetail userDetail = db.UserDetails.Find(id);
            if (userDetail == null)
            {
                return HttpNotFound();
            }
            return View(userDetail);
        }

        [Authorize(Roles = "Admin")]
        // POST: UserDetails/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserId,FirstName,LastName")] UserDetail userDetail)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userDetail).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userDetail);
        }

        [Authorize(Roles = "Admin")]
        // GET: UserDetails/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserDetail userDetail = db.UserDetails.Find(id);
            if (userDetail == null)
            {
                return HttpNotFound();
            }
            return View(userDetail);
        }

        [Authorize(Roles = "Admin")]
        // POST: UserDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            UserDetail userDetail = db.UserDetails.Find(id);
            db.UserDetails.Remove(userDetail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FinalProjectThatWorks.UI.MVC/Views/Shared/Original_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    @if (Request.IsAuthenticated && User.IsInRole("Admin")) {
                        <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                        <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FinalProjectThatWorks.UI.MVC/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!--Begin Document-->
<!DOCTYPE HTML>
<html>

<!--Head Section-->
<head>
    <!--Character Set-->
    <meta charset="utf-8">

    <!--Viewport-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--Tags-->
    <meta name="description" content="">
    <meta name="author" content="">

    <!--Favicon-->
    <link rel="shortcut icon" href="~/Content/assets/img/favicon.ico">

    <!--Page Title-->
    <title>Car Repair Application</title>

    <!--Style Sheets-->
    <link href="~/Content/assets/css/bootstrap.css" rel="stylesheet">
    <link href="~/Content/assets/css/animate.css" rel="stylesheet">
    <link href="~/Content/assets/css/prettyPhoto.css" rel="stylesheet">
    <link href="~/Content/assets/css/pe-icons.css" rel="stylesheet">
    <link href="~/Content/assets/css/style.css" rel="stylesheet">
    <link href="~/Content/assets/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/Content/custom.css" rel="stylesheet" />

    <!--Fonts-->
    <link href='http://fonts.googleapis.com/css?family=Cabin:300,400,700,300italic,400italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:400,300,700' rel='stylesheet' type='text/css'>

    <!--Scripts-->
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    <script src="~/Content/assets/js/jquery.js"></script>
    <script src="~/Content/assets/js/modernizr.custom.js"></script>    
</head>
<!--Head Section-->
<!--Body Section-->
<body>
    <!-- Preloader -->
    <div id="preloader"></div>  

    <!-- Nav -->
    <nav class="menu" id="theMenu">
        <div class="menu-wrap">
            <i class="fa fa-bars menu-close"></i>
            <div id="menu-logo">
                <h2><span class="pe-7s-chat logo-icon"></span> Main Menu </h2>
            </div>
            <ul id="main-menu">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Home <i class="fa fa-home menu-icon"></i></a>
                    <ul class="dropdown-menu">
                        <li><a href="@Url.Action("Index", "Home")">Home</a></li>
                        <li><a href="@Url.Action("Contact", "Home")">Contact Us</a></li>                        
                        @if (User.IsInRole("Employee"))
                        {
                            <li><a href="@Url.Action("Index", "Reservations")">Reservations</a></li>
                            <li><a href="@Url.Action("Index", "Locations")">Locations</a></li>
                            <li><a href="@Url.Action("Index", "Cars")">Cars</a></li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li><a href="@Url.Action("Index", "Reservations")">Reservations</a></li>
                            <li><a href="@Url.Action("Index", "Locations")">Locations</a></li>
                            <li><a href="@Url.Action("Index", "Cars")">Cars</a></li>
                            <li><a href="@Url.Action("Index", "UserDetails")">User Details</a></li>
                            <li><a href="@Url.Action("Index", "UsersAdmin")">UsersAdmin</a></li>
                            <li><a href="@Url.Action("Index", "RolesAdmin")">RolesAdmin</a></li>
                        }
                        @if (User.IsInRole("Owner"))
                        {
                            <li><a href="@Url.Action("Index", "Reservations")">Reservations</a></li>
                            <li><a href="@Url.Action("Index", "Locations")">Locations</a></li>
                            <li><a href="@Url.Action("Index", "Cars")">Cars</a></li>
                        }
                        <li><a href="~/Content/MackJonesDocumentation.pdf">Project Documentation</a></li>
                        @Html.Partial("_LoginPartial")
                    </ul>
                </li>
            </ul>
        </div>
    </nav>

    <!--Main Content Section-->
    <div id="mainContent">
       @RenderBody()
    </div>    
    <!--Main Content Section-->
    <!--Footer Content-->
    <!-- Footer -->
    <div id="footerwrap">
        <div id="footer-copyright">
            <div class="container">
                &copy; 2021 Mack Jones | Template By Distinctive Themes
            </div>
        </div>
    </div>

    <a id="gototop" class="gototop no-display" href="#"><i class="fa fa-angle-up"></i></a>

    <!-- Scripts -->
    <script src="~/Content/assets/js/bootstrap.min.js"></script>
    <script src="~/Content/assets/js/plugins.js"></script>
    <script src="~/Content/assets/js/imagesloaded.js"></script>
    <script src="~/Content/assets/js/prettyPhoto.js"></script>
    <script src="~/Content/assets/js/init.js"></script>
    @RenderSection("scripts", required: false)
</body>
    <!--Body Section-->
</html>
<!--End Document-->